image: $CI_JOB_IMAGE

stages:
  - build

import_sdk_and_compile:
  tags:
    - tqmaxx
  stage: build
  before_script:
    - echo "Importing and patching SDK"
    - scripts/prepare.sh
  script:
    - echo "Building targets"
    - scripts/build.sh
  artifacts:
    when: on_success
    paths:
      - "./build/artifacts/*.tar.gz"
