image: $CI_JOB_IMAGE

stages:
  - build

variables:
  ARMGCC_DIR: /opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi
  PROJECT_NAME: mcuxsdk-examples-tq
  BUILD_DIR: ./build
  ARTIFACTS_DIR: ./artifacts
  FORMAT: tar.gz

import_sdk_and_compile:
  tags:
    - tqmaxx
  stage: build
  before_script:
    - echo "Importing and patching SDK"
    - scripts/prepare.sh
  script:
    - echo "Building targets"
    - scripts/build.sh --build-dir "${BUILD_DIR}"
  after_script:
    - echo "Archiving"
    - gitrev=$("scripts/git-revision-name.sh")
    - scripts/create_artifacts.sh --format "${FORMAT}" --prefix "${PROJECT_NAME}.${gitrev}." --build-dir "${BUILD_DIR}" --output_path "${ARTIFACTS_DIR}"

  artifacts:
    when: on_success
    paths:
      - "${ARTIFACTS_DIR}/*.${FORMAT}"
