# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: nxp-mcuxpresso
      url-base: https://github.com/nxp-mcuxpresso

  projects:
    - name: mcuxsdk-manifests
      west-commands: scripts/west_commands.yml
      remote: nxp-mcuxpresso
      revision: v26.06.00-LTS
      path: mcuxpresso-sdk
      import:
      - submanifests/base.yml
      - submanifests/internal.yml
      - submanifests/devices/RT.yml
      - submanifests/devices/i.MX.yml
      - submanifests/middleware/eiq.yml
      - submanifests/middleware/multicore.yml
      - submanifests/rtos/rtos.yml

  group-filter:
  - -optional
  - -bifrost
  - -ble_cs_algo_private
  - -ble_cs_algo-restricted_private
  - -bluetooth_private
  - -fw_v19_nb
