# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2024 NXP
#
# Copyright (c) 2026 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel, Isaac Lucas de Lima Yuki
#

CONFIG_MCUX_HW_DEVICE_PART_MIMX8ML8DVNLZ=y

# Custom board basic segments
CONFIG_MCUX_PRJSEG_module.custom_board.common_folder=y
CONFIG_MCUX_PRJSEG_module.custom_board.boardfile_common_folder=y
CONFIG_MCUX_PRJSEG_module.custom_board.clock_common_folder=y
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_common_folder=y
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_common_folder=y

# Mcuxsdk internal board project basic segments all should be set to n
CONFIG_MCUX_PRJSEG_module.board.clock_board_folder=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
