CONFIG_MCUX_COMPONENT_driver.flexcan=y
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_common_folder=n
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_project_folder=y
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_common_folder=n
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_project_folder=y
