# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2025-2026 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Isaac Lucas de Lima Yuki
#

CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_common_folder=n
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_project_folder=y
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_common_folder=n
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_project_folder=y
