#!/bin/bash
# ****************************************************************************
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2021-2026 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Maximilian Kürth
#
# Description: Script to generate version header based on information 
# from VCS
#******************************************************************************

set -e
set -C # noclobber

# TRAP SIGNALS
trap 'error_abort $LINENO' ERR

function error_abort () {
	echo "error at $1" >&2
}

SCRIPTPATH=$(dirname "$(readlink -f "${0}")")
readonly SCRIPTPATH

function main () {
    local -r FILENAME=version.h
    local -r FILE=${FILENAME}
    local VERSION
    local BRANCH

    VERSION=$("${SCRIPTPATH}/git-revision-name.sh")
    BRANCH="$(git branch --show-current)"

    echo "generating version information header: ${VERSION}"

    rm -f "${FILE}"

    cat <<END  > "${FILE}"
//*****************************************************************************
/*!
 * \\\file  ${FILENAME}
 * \\\brief Auto generated version information file.
 * \\\note  Do not edit this file.
 */
//*****************************************************************************

#ifndef VERSION_H
#define VERSION_H

///! Defines the plain version string.
#define VERSION      "${VERSION}"
///! Defines the current branch in VCS.
#define BRANCH       "${BRANCH}"

#endif
END
}

main "$@"
