# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2024 NXP
#
# Copyright (c) 2025-2026 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel
#

CONFIG_MCUX_COMPONENT_driver.mu1=y
CONFIG_MCUX_COMPONENT_driver.sema42=y
CONFIG_MCUX_COMPONENT_driver.edma4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
# CONFIG_MCUX_MISC_middleware.freertos_generate_config=n
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.ns=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.queue=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.freertos=y

CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_common_folder=y
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_common_folder=n
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_project_folder=y
