# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2025-2026 TQ-Systems GmbH <oss@ew.tq-group.com>,
# D-82229 Seefeld, Germany.
# Author: Markus Niebel, Mohammad Tawsif Ahmad Ansari
#

CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.queue=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.ns=y
CONFIG_MCUX_COMPONENT_middleware.multicore.rpmsg-lite.freertos=y
CONFIG_MCUX_COMPONENT_middleware.eiq.ethosu.application=y
CONFIG_MCUX_COMPONENT_middleware.eiq.ethosu.core_driver=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.source=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.cmsis_nn=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.ethosu=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.debug_log=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MCUX_PRJSEG_module.board.boardfile_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_module.custom_board.pinmux_common_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_common_folder=n
CONFIG_MCUX_PRJSEG_project.custom_board.hw_app_project_folder=y
